import './site-toogle.js';
import './catalog-toogle.js';
import './intro.js';
import './filter-slider.js';
import './card-slider.js';
import './products-slider.js';
import './promo.js';
import './brands-slider.js';
import './reviews-slider.js';
